# Generated by Django 4.1.4 on 2022-12-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videos',
            field=models.FileField(upload_to='youtube/%y'),
        ),
    ]
